macro print_expression_info(expression_arg)
    println("--- Inside Macro '@print_expression_info' (Compile Time) ---")
    println("  Received expression:   ", expression_arg)
    println("  Type of expression:    ", typeof(expression_arg))
    println("  String representation: ", string(expression_arg))

    returned_expr = quote
        println("--- Executing Code Generated by Macro (Runtime) ---")
        println("  Original expression was: '", $(string(expression_arg)), "'")
        local result_value = $(expression_arg)
        println("  Its runtime value is:  ", result_value)
    end

    println("--- Macro Returning Expression ---")
    println(returned_expr)
    println("----------------------------------")

    return returned_expr
end

println("--- Script Execution (Runtime) ---")
println("Preparing to call the macro...")

@print_expression_info(1 + 2 * 3)
println("\nPreparing to call the macro with a variable...")
my_var = 100
@print_expression_info(my_var / 2)

println("\nScript finished.")
